image: gitpod/workspace-full:latest

tasks:
  - name: infrastructure
    before: |
      echo 'Bringing down any previously running containers'
    init: |
      cd deployment
      docker-compose down -v
  - name: postgres_db
    init: |
      cd deployment
      echo 'Starting postgres_db container'
      docker-compose up -d postgres_db
      echo 'Started postgres_db'
  - name: api
    init: |
      cd deployment
      # Set CORS origins for API
      export ALLOWED_ORIGINS="['$(gp url 3000)']"
      echo "ALLOWED_ORIGINS set to: $ALLOWED_ORIGINS"
      echo 'Building api container'
      docker-compose build api
      echo 'Built api'
    command: |
      gp await-port 6000
      cd deployment
      export ALLOWED_ORIGINS="['$(gp url 3000)']"
      echo 'Starting api container'
      docker-compose up -d api
      echo 'Started api'
  - name: python-backend
    init: |
      cd deployment
      # Set CORS origins for python-backend
      export ALLOWED_ORIGINS="['$(gp url 3000)']"
      echo "ALLOWED_ORIGINS set to: $ALLOWED_ORIGINS"
      echo 'Building python-backend container'
      docker-compose build python-backend
      echo 'Built python-backend'
    command: |
      gp await-port 6000
      cd deployment
      export ALLOWED_ORIGINS="['$(gp url 3000)']"
      echo 'Starting python-backend container'
      docker-compose up -d python-backend
      echo 'Started python-backend'
  - name: react-web
    init: |
      cd deployment
      # Set environment variables for the frontend
      export VITE_API_BASE_URL=$(gp url 5000)
      export VITE_PYTHON_API_BASE_URL=$(gp url 8300)/api/v1
      
      # Create .env file in web directory
      echo "VITE_API_BASE_URL=$VITE_API_BASE_URL" > ../web/.env
      echo "VITE_PYTHON_API_BASE_URL=$VITE_PYTHON_API_BASE_URL" >> ../web/.env
      
      echo "Environment variables set:"
      echo "VITE_API_BASE_URL=$VITE_API_BASE_URL"
      echo "VITE_PYTHON_API_BASE_URL=$VITE_PYTHON_API_BASE_URL"
      
      echo 'Building react-web container'
      docker-compose build react-web
      echo 'Built react-web'
    command: |
      gp await-port 5000
      gp await-port 8300
      cd deployment
      echo 'Starting react-web container'
      docker-compose up -d react-web
      echo 'Started react-web'

ports:
  - name: react-web
    description: Port 3000 for the react-web
    port: 3000
    onOpen: open-preview
    visibility: public
  - name: api
    description: Port 5000 for the api
    port: 5000
    onOpen: notify
    visibility: public
  - name: python-backend
    description: Port 8300 for the python-backend
    port: 8300
    onOpen: notify
    visibility: public
  - name: postgres_db
    description: Port 6000 for the postgres_db
    port: 6000
    onOpen: ignore
